I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 126, in script call
    call book_pre_reading_loc("books/barracs_iomedae_","barracs_loc")
  File "game/script.rpy", line 81, in script call
    call book_reading_loc(BookNameLocal, CallBackLocal)
  File "game/script.rpy", line 121, in script
    python:
  File "game/script.rpy", line 122, in <module>
    rnpy.jump(CallBackLocal)
NameError: name 'rnpy' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 126, in script call
    call book_pre_reading_loc("books/barracs_iomedae_","barracs_loc")
  File "game/script.rpy", line 81, in script call
    call book_reading_loc(BookNameLocal, CallBackLocal)
  File "game/script.rpy", line 121, in script
    python:
  File "renpy/ast.py", line 923, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2235, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 122, in <module>
    rnpy.jump(CallBackLocal)
NameError: name 'rnpy' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
randal_may_monastry 1.0
Tue Sep 28 03:36:27 2021
