I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 93, in script call
    call screen monastry_map
  File "game/add.rpy", line 69, in script
    $ renpy.jump_out_of_context(str(NextLocation))
  File "game/add.rpy", line 69, in <module>
    $ renpy.jump_out_of_context(str(NextLocation))
JumpOutException: barracs_loc

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 617, in main
    run(restart)
  File "renpy/main.py", line 148, in run
    renpy.execution.run_context(True)
  File "renpy/execution.py", line 922, in run_context
    context.run()
  File "game/script.rpy", line 93, in script call
    call screen monastry_map
  File "game/add.rpy", line 69, in script
    $ renpy.jump_out_of_context(str(NextLocation))
  File "renpy/ast.py", line 923, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2235, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/add.rpy", line 69, in <module>
    $ renpy.jump_out_of_context(str(NextLocation))
  File "renpy/exports.py", line 1921, in jump_out_of_context
    raise renpy.game.JumpOutException(label)
JumpOutException: barracs_loc

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
randal_may_monastry 1.0
Fri Oct  8 03:51:30 2021
