I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 53, in script call
    call diary_main
  File "game/script.rpy", line 53, in script call
    call diary_main
ScriptError: could not find label 'diary_main'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 53, in script call
    call diary_main
  File "renpy/ast.py", line 1485, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 53, in script call
    call diary_main
  File "renpy/script.py", line 918, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'diary_main'.

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
randal_may_monastry 1.0
Mon Oct  4 03:02:40 2021
