I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 501, in script call
    call monastry_map_loc
  File "game/script.rpy", line 516, in script call
    call screen monastry_map
  File "game/add.rpy", line 737, in script call
    call screen show_location_items
  File "game/add.rpy", line 737, in script call
    call screen show_location_items
  File "game/add.rpy", line 737, in script call
    call screen show_location_items
  File "game/add.rpy", line 726, in script
    python:
  File "game/add.rpy", line 728, in <module>
    renpy.call(monastry_map_loc)
NameError: name 'monastry_map_loc' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 501, in script call
    call monastry_map_loc
  File "game/script.rpy", line 516, in script call
    call screen monastry_map
  File "game/add.rpy", line 737, in script call
    call screen show_location_items
  File "game/add.rpy", line 737, in script call
    call screen show_location_items
  File "game/add.rpy", line 737, in script call
    call screen show_location_items
  File "game/add.rpy", line 726, in script
    python:
  File "D:\renpy-8.0.2-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy-8.0.2-sdk\renpy\python.py", line 1052, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/add.rpy", line 728, in <module>
    renpy.call(monastry_map_loc)
NameError: name 'monastry_map_loc' is not defined

Windows-10-10.0.19042 AMD64
Ren'Py 8.0.2.22081402
randal_may_monastry 1.0
Sun Aug 28 23:46:12 2022
